ADD_COMPILE_DEFINITIONS(-DCL_HPP_TARGET_OPENCL_VERSION=220
                        -DCL_HPP_CL_1_2_DEFAULT_BUILD
                        -DCL_HPP_ENABLE_EXCEPTIONS
                        -DCL_QUEUE_PROFILING_ENABLE)
